---
- hosts: all
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
  
  - name: Change ansible user password
    user:
      name: ansible
      update_password: always
      password: "{{ 'new_password_here'|password_hash('sha512') }}"
