---
- name: IP Address Modifications
  hosts: all
  remote_user: ansible
  become: yes
  become_user: root
  tasks:

  - name: Disable IPv6
    copy:
      dest: "/etc/sysctl.d/disable-ipv6.conf"
      content: "net.ipv6.conf.all.disable_ipv6 = 1"
      owner: root
      group: root
      mode: 0644
