---
- name: Update pihole version
  hosts: all
  remote_user: ansible
  become: yes
  become_user: root
  tasks:

  - name: Collect facts
    setup:
  
  - name: Update pihole
    command: sudo pihole -up
